name: 'Terraform-Push-MY'

on:
  push:
   branches:
    - staging
   paths:
      - MY/** 

jobs:
  terraform_apply:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-southeast-1"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MY
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      env:
            TERRAFORM_VERSION: "1.0.5"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    - name: Terraform init
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate

    - name: Terraform apply
      run: terraform apply -auto-approve -input=false